(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/cloudPage"],{"3e1f":function(t,e,n){"use strict";n.r(e);var u=n("d56d"),a=n("5f48");for(var r in a)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return a[t]}))}(r);n("69db");var d,o=n("f0c5"),i=Object(o["a"])(a["default"],u["b"],u["c"],!1,null,null,null,!1,u["a"],d);e["default"]=i.exports},"5f48":function(t,e,n){"use strict";n.r(e);var u=n("86da"),a=n.n(u);for(var r in u)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return u[t]}))}(r);e["default"]=a.a},"69db":function(t,e,n){"use strict";var u=n("cb24"),a=n.n(u);a.a},"86da":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{customHeader:{type:Boolean,default:!0},headerHeight:{type:Number,default:44},headerIndex:{type:Number,default:1},headerBG:{type:String,default:"none"},statusBarBG:{type:String,default:"none"},footerIndex:{type:Number,default:1},footerBg:{type:String,default:""},isSwitchPage:{type:Boolean,default:!1},rbWidth:{type:Number,default:100},rbBottom:{type:Number,default:100},rbRight:{type:Number,default:20},rbIndex:{type:Number,default:1},borderWidth:{type:String,default:"0"},borderColor:{type:String,default:"#D1D1D1"},loadingBG:{type:String,default:"rgba(255,255,255, 0.1)"},isLoading:{type:Boolean,default:!1},loadingPointBg:{type:String,default:"#3688FF"}},data:function(){return{statusBarHeight:0,iphoneXButtomHeight:0,BoundingWidth:"0px"}},created:function(){try{var e=t.getSystemInfoSync();e.model=e.model.replace(" ",""),e.model=e.model.toLowerCase(),-1==e.model.indexOf("iphonex")&&-1==e.model.indexOf("iphone11")||(this.iphoneXButtomHeight=t.upx2px(50))}catch(n){return null}if(this.customHeader){this.statusBarHeight=e.statusBarHeight;e=t.getMenuButtonBoundingClientRect();this.BoundingWidth=e.width+20+"px"}}};e.default=n}).call(this,n("543d")["default"])},cb24:function(t,e,n){},d56d:function(t,e,n){"use strict";var u;n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return r})),n.d(e,"a",(function(){return u}));var a=function(){var t=this,e=t.$createElement;t._self._c},r=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/cloudPage-create-component',
    {
        'components/cloudPage-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("3e1f"))
        })
    },
    [['components/cloudPage-create-component']]
]);
